[package]
name = "bank-converter"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
serde-xml-rs = "0.8"

[[example]]
name = "cli"
path = "src/examples/cli.rs"
